### ISSUE TITLE
upcoming features point to google.

### ISSUE THREAD

**Issue by woolensculpture** [JPBetley/pulse#87]
cd signout and work hours on the dj page currently point to google, since these features are unlikely to be implemented soon they should be disabled possibly with a note next to them.

**Comment by JPBetley** [comment]
Those two links should be configurable through the System Settings area of the app. You can just change them to be whatever when needed. I believe we have the links for the current Google Forms versions of both of these things in an email chain or something, so they can be put there when we deploy to production. I just didn't want our links publicly available in this repo, so gave them default values of https://google.com. Stop bots from scanning and getting access to the forms we use

**Comment by woolensculpture** [comment]
thanks for letting letting me know, I'll make note of that and change it during staging.
